### ISSUE TITLE
Images on jumbotron get squished on mobile

### ISSUE THREAD

**Issue by jackwherry** [eado/portfolio-test-website#1]
When using a low screen resolution, the collage of images that are behind the jumbotron are squished and look distorted.

**Comment by jackwherry** [comment]
This doesn't seem to be the case when resizing Chrom(ium) windows, but when I use Slide Over on iPad or a cell phone the images get squished.

**Comment by eado** [comment]
Plus, it's not a Jumbotron, it's a single item carousel.

**Comment by eado** [comment]
Looking into it....

**Comment by eado** [comment]
I think you are using an old version of Chrome that doesn't support the CSS statement `object-fit: cover`. `object-fit: cover` makes it so that it fills the screen, but in regard to the current aspect ratio of the image.
