### ISSUE TITLE
Selfie with Raspberry Pi is out of focus

### ISSUE THREAD

**Issue by jackwherry** [eado/portfolio-test-website#2]
In contrast to the good-looking other parts of the website, the first thing that the user sees (the selfie) is out of focus and not professional-looking.

**Comment by eado** [comment]
'Fist thing' definitely professional. Anyways, its just a test website; it doesn't matter.

**Comment by eado** [comment]
*it's

**Comment by eado** [comment]
*'Fist thing' is

**Comment by jackwherry** [comment]
We're even on typos 😉.
